# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vaultwright < Formula
  desc "Build an encrypted, embedded static-file server from a single binary"
  homepage "https://github.com/alexey-lapin/vaultwright"
  version "0.0.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.4/vaultwright_0.0.4_darwin_amd64.tar.gz"
      sha256 "64f74a69cc21eb8c06d916d1045cfadefcefdb7f50c56d1e17dfa9f5662d8eee"

      define_method(:install) do
        bin.install "vaultwright"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.4/vaultwright_0.0.4_darwin_arm64.tar.gz"
      sha256 "cca1a4f5d3b40949e028614863be86cd075c53228808594852159f669ae3069e"

      define_method(:install) do
        bin.install "vaultwright"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.4/vaultwright_0.0.4_linux_amd64.tar.gz"
      sha256 "0fd45016210588ecccab1b2e431a647c7966fcbad4782e37fb4d579654f5a7e6"
      define_method(:install) do
        bin.install "vaultwright"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.4/vaultwright_0.0.4_linux_arm64.tar.gz"
      sha256 "273aad9211c8fc6674c24b3be6a7de25aa01799fe7accbe5523285ccdb46cf13"
      define_method(:install) do
        bin.install "vaultwright"
      end
    end
  end

  test do
    assert_match "vaultwright", shell_output("#{bin}/vaultwright version")
  end
end
