# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vaultwright < Formula
  desc "Build an encrypted, embedded static-file server from a single binary"
  homepage "https://github.com/alexey-lapin/vaultwright"
  version "0.0.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.5/vaultwright_0.0.5_darwin_amd64.tar.gz"
      sha256 "ba8205b6d9acbb59f9c210257f7d4cae961980dcab4ab3980372a579fd6c3464"

      define_method(:install) do
        bin.install "vaultwright"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.5/vaultwright_0.0.5_darwin_arm64.tar.gz"
      sha256 "76c959a9cf516de267e3943165f8070a973b9e6c4b234f0913d4c7fcd18f12c8"

      define_method(:install) do
        bin.install "vaultwright"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.5/vaultwright_0.0.5_linux_amd64.tar.gz"
      sha256 "7b2e43cc0a7278166289d2d96adf0db91caae655ff1560ddf26772d1fdcbef8e"
      define_method(:install) do
        bin.install "vaultwright"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.5/vaultwright_0.0.5_linux_arm64.tar.gz"
      sha256 "4ced13b6aab4cdb59afada935b8b4fbfa09a9ac3cbc1d54b4125354aeb100823"
      define_method(:install) do
        bin.install "vaultwright"
      end
    end
  end

  test do
    assert_match "vaultwright", shell_output("#{bin}/vaultwright version")
  end
end
