# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vaultwright < Formula
  desc "Build an encrypted, embedded static-file server from a single binary"
  homepage "https://github.com/alexey-lapin/vaultwright"
  version "0.0.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.6/vaultwright_0.0.6_darwin_amd64.tar.gz"
      sha256 "3bdabc2de4c44d9b0a3d4ddcf32f283c0d1fa05ba68140a27027de55f994e889"

      define_method(:install) do
        bin.install "vaultwright"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.6/vaultwright_0.0.6_darwin_arm64.tar.gz"
      sha256 "48fd6dbb826267eab09885e4b6ec9532cde1f2695c5b615f7115ef05fc07e384"

      define_method(:install) do
        bin.install "vaultwright"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.6/vaultwright_0.0.6_linux_amd64.tar.gz"
      sha256 "5d947097771839a0f0f0df867ffc4d2b204c4a2d5e948f0fc609511a18209c97"
      define_method(:install) do
        bin.install "vaultwright"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.6/vaultwright_0.0.6_linux_arm64.tar.gz"
      sha256 "ebf6d14c65148bfc7ee35f6986d7af5024ef19db5f20c6d9da79e690f36b031d"
      define_method(:install) do
        bin.install "vaultwright"
      end
    end
  end

  test do
    assert_match "vaultwright", shell_output("#{bin}/vaultwright version")
  end
end
