# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vaultwright < Formula
  desc "Build an encrypted, embedded static-file server from a single binary"
  homepage "https://github.com/alexey-lapin/vaultwright"
  version "0.0.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.8/vaultwright_0.0.8_darwin_amd64.tar.gz"
      sha256 "f4d428fe98fa3f9f2565339f67eabbf08d82bee0bc06d07d7589fa95f4771b06"

      define_method(:install) do
        bin.install "vaultwright"
        bash_completion.install "completions/vaultwright.bash" => "vaultwright"
        zsh_completion.install "completions/vaultwright.zsh" => "_vaultwright"
        fish_completion.install "completions/vaultwright.fish" => "vaultwright.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.8/vaultwright_0.0.8_darwin_arm64.tar.gz"
      sha256 "b4816b8b5d7645122f71ff7d800ea40111fa1f4f2c23f3e7ddd324caaa915dc2"

      define_method(:install) do
        bin.install "vaultwright"
        bash_completion.install "completions/vaultwright.bash" => "vaultwright"
        zsh_completion.install "completions/vaultwright.zsh" => "_vaultwright"
        fish_completion.install "completions/vaultwright.fish" => "vaultwright.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.8/vaultwright_0.0.8_linux_amd64.tar.gz"
      sha256 "9561bb1b3d0b2e25e7299dd1f3470c91ca47e0030512e73b7fa3292ae8f7dcc8"
      define_method(:install) do
        bin.install "vaultwright"
        bash_completion.install "completions/vaultwright.bash" => "vaultwright"
        zsh_completion.install "completions/vaultwright.zsh" => "_vaultwright"
        fish_completion.install "completions/vaultwright.fish" => "vaultwright.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alexey-lapin/vaultwright/releases/download/v0.0.8/vaultwright_0.0.8_linux_arm64.tar.gz"
      sha256 "0bbcb86240b09ffa318215740b78539213f7a136e3039e0eed34bbe860cdbd4b"
      define_method(:install) do
        bin.install "vaultwright"
        bash_completion.install "completions/vaultwright.bash" => "vaultwright"
        zsh_completion.install "completions/vaultwright.zsh" => "_vaultwright"
        fish_completion.install "completions/vaultwright.fish" => "vaultwright.fish"
      end
    end
  end

  test do
    assert_match "vaultwright", shell_output("#{bin}/vaultwright version")
  end
end
